# Generated by Django 6.0.4 on 2026-04-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('policy_defaults', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant'), ('runtime', 'Runtime')], default='platform', max_length=32)),
                ('provider_kind', models.CharField(choices=[('openrouter', 'OpenRouter'), ('openai', 'OpenAI'), ('openai-compatible', 'OpenAI Compatible'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('custom', 'Custom')], max_length=64)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('verified', 'Verified'), ('error', 'Error'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='pending', max_length=32)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_secret_name', models.CharField(blank=True, max_length=255)),
                ('api_base_secret_name', models.CharField(blank=True, max_length=255)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('live', 'Live'), ('probe', 'Probe'), ('limit-probe', 'Limit Probe'), ('playground', 'Playground'), ('custom', 'Custom')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('defaults', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=32)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('provider_model', models.CharField(max_length=255)),
                ('is_platform_default', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('model_info', models.JSONField(blank=True, default=dict)),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='domain.providerconnection')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_models', to='domain.tenant')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runtime_id', models.SlugField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('gateway_port', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=255)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('desired_channels', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('infisical_project_slug', models.CharField(max_length=255)),
                ('infisical_project_id', models.CharField(max_length=255)),
                ('infisical_env', models.CharField(default='prod', max_length=64)),
                ('infisical_path', models.CharField(default='/runtime', max_length=255)),
                ('litellm_key_name', models.CharField(blank=True, max_length=255)),
                ('litellm_budget_usd', models.FloatField(blank=True, null=True)),
                ('litellm_rpm_limit', models.IntegerField(blank=True, null=True)),
                ('litellm_tpm_limit', models.IntegerField(blank=True, null=True)),
                ('litellm_model_alias', models.CharField(default='openai/qwen/qwen3.6-plus', max_length=255)),
                ('litellm_price_input_per_million_usd', models.FloatField(blank=True, null=True)),
                ('litellm_price_output_per_million_usd', models.FloatField(blank=True, null=True)),
                ('runtime_env_file', models.CharField(max_length=1024)),
                ('runtime_home', models.CharField(max_length=1024)),
                ('workspace_dir', models.CharField(max_length=1024)),
                ('generated_config_path', models.CharField(max_length=1024)),
                ('lifecycle_status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('unknown', 'Unknown')], default='created', max_length=32)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('last_healthcheck_at', models.DateTimeField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('default_provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_runtimes', to='domain.providerconnection')),
                ('default_provider_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_runtimes', to='domain.providermodel')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtimes', to='domain.plan')),
                ('runtime_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtimes', to='domain.runtimeprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtimes', to='domain.tenant')),
            ],
            options={
                'ordering': ['runtime_id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('gitea', 'Gitea'), ('kanboard', 'Kanboard'), ('search', 'Search'), ('openwebui', 'OpenWebUI')], max_length=64)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant'), ('runtime', 'Runtime')], default='runtime', max_length=32)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('verified', 'Verified'), ('error', 'Error'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='pending', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='domain.runtime')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='domain.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('verified', 'Verified'), ('error', 'Error'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='pending', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='domain.runtime')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('verified', 'Verified'), ('error', 'Error'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='configured', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='domain.runtime')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=32)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='domain.runtimechatsession')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeDiagnosticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('logs', models.JSONField(blank=True, default=dict)),
                ('traces', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('runtime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_snapshot', to='domain.runtime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeSecretRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(unique=True)),
                ('secret_kind', models.CharField(choices=[('provider_api_key', 'Provider API Key'), ('provider_api_base', 'Provider API Base'), ('telegram_bot_token', 'Telegram Bot Token'), ('telegram_allow_from', 'Telegram Allow From'), ('slack_bot_token', 'Slack Bot Token'), ('slack_app_token', 'Slack App Token'), ('slack_signing_secret', 'Slack Signing Secret'), ('mattermost_bot_token', 'Mattermost Bot Token'), ('gitea_token', 'Gitea Token'), ('kanboard_password', 'Kanboard Password'), ('search_api_key', 'Search API Key')], max_length=64)),
                ('infisical_project_id', models.CharField(max_length=255)),
                ('infisical_env', models.CharField(default='prod', max_length=64)),
                ('infisical_path', models.CharField(default='/runtime', max_length=255)),
                ('secret_name', models.CharField(max_length=255)),
                ('masked_label', models.CharField(blank=True, max_length=255)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('integration_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='domain.integrationconnection')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='domain.providerconnection')),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='domain.runtime')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_refs', to='domain.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='domain.tenant'),
        ),
    ]
