# Generated by Django 6.0.4 on 2026-05-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('launching', 'Launching'), ('running', 'Running'), ('stopped', 'Stopped'), ('degraded', 'Degraded'), ('error', 'Error')], default='draft', max_length=32)),
                ('primary_channel', models.CharField(choices=[('telegram', 'Telegram'), ('internal', 'Internal')], default='telegram', max_length=32)),
                ('last_launched_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SkillCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('source_path', models.CharField(max_length=1024)),
                ('compatibility_rules', models.JSONField(blank=True, default=dict)),
                ('default_enabled', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('authelia_subject', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('infisical_project_slug', models.CharField(default='workspace-default', max_length=255)),
                ('infisical_project_id', models.CharField(blank=True, max_length=255)),
                ('infisical_env', models.CharField(default='prod', max_length=64)),
                ('infisical_path', models.CharField(default='/workspace', max_length=255)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentBuildSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personality_prompt', models.TextField(blank=True)),
                ('model_alias', models.CharField(default='openai/qwen/qwen3.6-plus', max_length=255)),
                ('runtime_template', models.CharField(default='generic-runtime', max_length=255)),
                ('gateway_port', models.PositiveIntegerField(default=0)),
                ('environment_profile', models.JSONField(blank=True, default=dict)),
                ('startup_policy', models.JSONField(blank=True, default=dict)),
                ('observability_profile', models.JSONField(blank=True, default=dict)),
                ('autonomy_limits', models.JSONField(blank=True, default=dict)),
                ('safety_limits', models.JSONField(blank=True, default=dict)),
                ('channel_config', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('litellm_budget_usd', models.FloatField(blank=True, null=True)),
                ('litellm_rpm_limit', models.IntegerField(blank=True, null=True)),
                ('litellm_tpm_limit', models.IntegerField(blank=True, null=True)),
                ('build_state', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('launching', 'Launching'), ('running', 'Running'), ('stopped', 'Stopped'), ('degraded', 'Degraded'), ('error', 'Error')], default='draft', max_length=32)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_specs', to='domain.agent')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='current_build_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.agentbuildspec'),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('launching', 'Launching'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('runtime_ref', models.CharField(blank=True, max_length=255)),
                ('launch_summary', models.JSONField(blank=True, default=dict)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='domain.agent')),
                ('build_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='domain.agentbuildspec')),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='domain.runtime')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='current_deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.deployment'),
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('secret_kind', models.CharField(choices=[('provider_api_key', 'Provider API Key'), ('provider_api_base', 'Provider API Base'), ('telegram_bot_token', 'Telegram Bot Token'), ('telegram_allow_from', 'Telegram Allow From'), ('slack_bot_token', 'Slack Bot Token'), ('slack_app_token', 'Slack App Token'), ('slack_signing_secret', 'Slack Signing Secret'), ('mattermost_bot_token', 'Mattermost Bot Token'), ('gitea_token', 'Gitea Token'), ('kanboard_password', 'Kanboard Password'), ('search_api_key', 'Search API Key')], max_length=64)),
                ('backend_ref', models.CharField(blank=True, max_length=255)),
                ('backend_secret_name', models.CharField(max_length=255)),
                ('usage_scope', models.CharField(default='workspace', max_length=64)),
                ('masked_label', models.CharField(blank=True, max_length=255)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='domain.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='domain.workspace'),
        ),
        migrations.CreateModel(
            name='AgentSecretBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_role', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('build_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_bindings', to='domain.agentbuildspec')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='domain.secret')),
            ],
            options={
                'ordering': ['logical_role'],
                'constraints': [models.UniqueConstraint(fields=('build_spec', 'logical_role'), name='unique_secret_role_per_build_spec')],
            },
        ),
        migrations.CreateModel(
            name='AgentSkillBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('build_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_bindings', to='domain.agentbuildspec')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='domain.skillcatalogentry')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('build_spec', 'skill'), name='unique_skill_per_build_spec'), models.UniqueConstraint(fields=('build_spec', 'position'), name='unique_skill_position_per_build_spec')],
            },
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_secret_name'),
        ),
    ]
