# Generated by Django 6.0.4 on 2026-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=1024)),
                ('compatibility_rules', models.JSONField(blank=True, default=dict)),
                ('default_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('skill_type', models.CharField(choices=[('behavior', 'Behavior'), ('hybrid', 'Hybrid'), ('executable', 'Executable')], default='behavior', max_length=32)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('nullclaw-registry', 'NullClaw Registry'), ('github', 'GitHub')], default='internal', max_length=64)),
                ('trust_status', models.CharField(choices=[('internal', 'Internal'), ('reviewed', 'Reviewed'), ('quarantine', 'Quarantine'), ('blocked', 'Blocked')], default='internal', max_length=32)),
                ('source_url', models.URLField(blank=True)),
                ('required_integrations', models.JSONField(blank=True, default=list)),
                ('required_secrets', models.JSONField(blank=True, default=list)),
                ('required_services', models.JSONField(blank=True, default=list)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('entrypoints', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['category', 'display_name', 'key'],
            },
        ),
    ]
