# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_agent_skillcatalogentry_workspace_agentbuildspec_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillcatalogentry",
            options={"ordering": ["category", "display_name", "key"]},
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("disabled", "Disabled")],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="skill_type",
            field=models.CharField(
                choices=[("behavior", "Behavior"), ("hybrid", "Hybrid"), ("executable", "Executable")],
                default="behavior",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="source",
            field=models.CharField(
                choices=[("internal", "Internal"), ("nullclaw-registry", "NullClaw Registry"), ("github", "GitHub")],
                default="internal",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="trust_status",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("reviewed", "Reviewed"),
                    ("quarantine", "Quarantine"),
                    ("blocked", "Blocked"),
                ],
                default="internal",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="required_integrations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="required_secrets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="required_services",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skillcatalogentry",
            name="entrypoints",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
